### ISSUE TITLE
site doesn't have actual username availability apart from reserved names

### ISSUE THREAD

**Issue by mm12** [Lixqa/DiscordPomelo#1]
This site only appears to check if the name is on the reserved names list, and says all other users are available. 
Steps to reproduce: enter a user who has had new username for several days (such as `vedal`)
Expected result: "username is taken"
Actual result: "username is available"

**Comment by Lixqa** [comment]
This issue got fixed 1 week ago. Let me know if you find any other issues. Also feel free to join my discord if you have any other questions! https://lix.qa/pomelo-dc
